[package]
name = "wasm-image"
version = "0.1.0"
authors = ["FuBaooo"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.75"
image = "0.23.14"
base64 = "0.13.0"
